# Generated by Django 5.2.4 on 2025-08-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
