# Generated by Django 5.2.4 on 2025-08-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_delete_at_chatmessage_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
